### ISSUE TITLE
Задача-галочка для закрытия Milestone

### ISSUE THREAD

**Issue by alexbaumgertner** [cantcool/id80994_nerds#10]
- [x] проверить в pixel perfect
- [x] сжать исправленные css и js
- [x] залить на проверку

**Comment by alexbaumgertner** [comment]
@cantcool посмотри по пунктам выше

**Comment by cantcool** [comment]
Чек-лист провел, залил на проверку.

**Comment by alexbaumgertner** [comment]
100%, поздравляю!!!!!

**Comment by cantcool** [comment]
:sparkles:
